add container specifying support

diff --git a/bin/kubectl-sshd b/bin/kubectl-sshd
--- a/bin/kubectl-sshd
+++ b/bin/kubectl-sshd
@@ -2,6 +2,7 @@
 
 # Created by argbash-init v2.8.1
 # ARG_POSITIONAL_SINGLE([pod],[Pod name],[])
+# ARG_OPTIONAL_SINGLE([container],[c],[Container name (if more than one container in Pod)],[])
 # ARG_OPTIONAL_SINGLE([local-dropbear-path],[l],[Local Path to statically-built dropbear/SSH server binary (default: $SCRIPT_DIR/static-dropbear)],[])
 # ARG_OPTIONAL_SINGLE([remote-dropbear-dir],[r],[Pod Path to upload dropbear/SSH server to],[/tmp])
 # ARG_OPTIONAL_SINGLE([remote-scp-path],[R],[Pod Path for scp],[/bin/scp])
@@ -9,7 +10,7 @@
 # ARG_OPTIONAL_SINGLE([authorized-keys-path],[k],[Public keys of those authorized to authenticate through SSH],[id_rsa.pub])
 # ARG_OPTIONAL_SINGLE([ssh-path],[s],[SSH Path Location, specify if authenticate using non-root user],[/root/.ssh])
 # ARG_OPTIONAL_SINGLE([namespace],[n],[Pod Namespace],[])
-# ARG_OPTIONAL_BOOLEAN([cleanup],[c],[Cleanup all the files and dropbear binary before script exits])
+# ARG_OPTIONAL_BOOLEAN([cleanup],[C],[Cleanup all the files and dropbear binary before script exits])
 # ARG_OPTIONAL_BOOLEAN([verbose],[V],[Increase verbosity of script])
 # ARG_DEFAULTS_POS()
 # ARG_HELP([kssh - Start a SSH server in any Pod])
@@ -34,7 +35,7 @@ die()
 
 begins_with_short_option()
 {
-  local first_option all_short_options='lrRbksncVhv'
+  local first_option all_short_options='clrRbksnCVhv'
   first_option="${1:0:1}"
   test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -43,6 +44,7 @@ begins_with_short_option()
 _positionals=()
 _arg_pod=
 # THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_container=
 _arg_local_dropbear_path=
 _arg_remote_dropbear_dir="/tmp"
 _arg_remote_scp_path="/bin/scp"
@@ -57,8 +59,9 @@ _arg_verbose="off"
 print_help()
 {
   printf '%s\n' "kssh - Start a SSH server in any Pod"
-  printf 'Usage: %s [-l|--local-dropbear-path <arg>] [-r|--remote-dropbear-dir <arg>] [-R|--remote-scp-path <arg>] [-b|--bind-port <arg>] [-k|--authorized-keys-path <arg>] [-s|--ssh-path <arg>] [-n|--namespace <arg>] [-c|--(no-)cleanup] [-V|--(no-)verbose] [-h|--help] [-v|--version] <pod>\n' "$0"
+  printf 'Usage: %s [-c|--container <arg>] [-l|--local-dropbear-path <arg>] [-r|--remote-dropbear-dir <arg>] [-R|--remote-scp-path <arg>] [-b|--bind-port <arg>] [-k|--authorized-keys-path <arg>] [-s|--ssh-path <arg>] [-n|--namespace <arg>] [-C|--(no-)cleanup] [-V|--(no-)verbose] [-h|--help] [-v|--version] <pod>\n' "$0"
   printf '\t%s\n' "<pod>: Pod name"
+  printf '\t%s\n' "-c, --container: Container name (if more than one container in Pod) (no default)"
   printf '\t%s\n' "-l, --local-dropbear-path: Local Path to statically-built dropbear/SSH server binary (default: $SCRIPT_DIR/static-dropbear) (no default)"
   printf '\t%s\n' "-r, --remote-dropbear-dir: Pod Path to upload dropbear/SSH server to (default: '/tmp')"
   printf '\t%s\n' "-R, --remote-scp-path: Pod Path for scp (default: '/bin/scp')"
@@ -66,7 +69,7 @@ print_help()
   printf '\t%s\n' "-k, --authorized-keys-path: Public keys of those authorized to authenticate through SSH (default: 'id_rsa.pub')"
   printf '\t%s\n' "-s, --ssh-path: SSH Path Location, specify if authenticate using non-root user (default: '/root/.ssh')"
   printf '\t%s\n' "-n, --namespace: Pod Namespace (no default)"
-  printf '\t%s\n' "-c, --cleanup, --no-cleanup: Cleanup all the files and dropbear binary before script exits (off by default)"
+  printf '\t%s\n' "-C, --cleanup, --no-cleanup: Cleanup all the files and dropbear binary before script exits (off by default)"
   printf '\t%s\n' "-V, --verbose, --no-verbose: Increase verbosity of script (off by default)"
   printf '\t%s\n' "-h, --help: Prints help"
   printf '\t%s\n' "-v, --version: Prints version"
@@ -80,6 +83,17 @@ parse_commandline()
   do
     _key="$1"
     case "$_key" in
+      -c|--container)
+        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+        _arg_container="$2"
+        shift
+        ;;
+      --container=*)
+        _arg_container="${_key##--container=}"
+        ;;
+      -c*)
+        _arg_container="${_key##-c}"
+        ;;
       -l|--local-dropbear-path)
         test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
         _arg_local_dropbear_path="$2"
@@ -157,16 +171,16 @@ parse_commandline()
       -n*)
         _arg_namespace="${_key##-n}"
         ;;
-      -c|--no-cleanup|--cleanup)
+      -C|--no-cleanup|--cleanup)
         _arg_cleanup="on"
         test "${1:0:5}" = "--no-" && _arg_cleanup="off"
         ;;
-      -c*)
+      -C*)
         _arg_cleanup="on"
-        _next="${_key##-c}"
+        _next="${_key##-C}"
         if test -n "$_next" -a "$_next" != "$_key"
         then
-          { begins_with_short_option "$_next" && shift && set -- "-c" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+          { begins_with_short_option "$_next" && shift && set -- "-C" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
         fi
         ;;
       -V|--no-verbose|--verbose)
@@ -250,6 +264,7 @@ done
 SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
 
 POD_NAME=$_arg_pod
+CONTAINER_NAME=$_arg_container
 SOURCE_PATH=$_arg_local_dropbear_path
 PAYLOAD_DIR=$_arg_remote_dropbear_dir
 PAYLOAD_PATH="${PAYLOAD_DIR}/dropbear"
@@ -272,26 +287,31 @@ then
     KUBECTL_CMD="${KUBECTL_CMD} -n ${NAMESPACE}"
 fi
 
+KUBECTL_CMD_CONT=$KUBECTL_CMD
+if [ ! -z "$CONTAINER_NAME" ];
+then
+    KUBECTL_CMD_CONT="${KUBECTL_CMD} -c ${CONTAINER_NAME}"
+fi
 
 copy_binary() {
-    $KUBECTL_CMD exec $POD_NAME ls $PAYLOAD_PATH > /dev/null 2>&1
+    $KUBECTL_CMD_CONT exec $POD_NAME ls $PAYLOAD_PATH > /dev/null 2>&1
     if [ $? -ne 0 ]
     then
         echo "Payload binary does not exist at $PAYLOAD_PATH. Uploading..."
-        $KUBECTL_CMD exec $POD_NAME -- mkdir -p $PAYLOAD_DIR
+        $KUBECTL_CMD_CONT exec $POD_NAME -- mkdir -p $PAYLOAD_DIR
         if [ $? -ne 0 ]
         then
             echo "Payload DIR $PAYLOAD_DIR could not be created. Aborting."
             exit 1
         fi
-        $KUBECTL_CMD cp $SOURCE_PATH $POD_NAME:$PAYLOAD_PATH
+        $KUBECTL_CMD_CONT cp $SOURCE_PATH $POD_NAME:$PAYLOAD_PATH
         if [ $? -eq 0 ]
         then
             echo "Payload uploaded to $PAYLOAD_PATH!"
             if [ ! -z "${REMOTE_SCP_PATH}" ]
             then
                 echo "Setting up scp symlink $REMOTE_SCP_PATH -> $PAYLOAD_PATH"
-                $KUBECTL_CMD exec $POD_NAME -- ln -s $PAYLOAD_PATH $REMOTE_SCP_PATH
+                $KUBECTL_CMD_CONT exec $POD_NAME -- ln -s $PAYLOAD_PATH $REMOTE_SCP_PATH
                 if [ $? -ne 0 ]
                 then
                     echo "Failed to symlink scp $REMOTE_SCP_PATH -> $PAYLOAD_PATH. Ignoring."
@@ -320,28 +340,28 @@ copy_keys() {
         echo "To generate a new keypair, run the following command: ssh-keygen -t rsa -N '' -f id_rsa"
         exit 2
     fi
-    $KUBECTL_CMD exec $POD_NAME -- mkdir -p $SSH_PATH
-    $KUBECTL_CMD cp $AUTHORIZED_KEYS_PATH $POD_NAME:$AUTHORIZED_KEYS_DEST
-    $KUBECTL_CMD exec $POD_NAME -- chmod 0600 -R $SSH_PATH
-    $KUBECTL_CMD exec $POD_NAME -- chown root:root -R $SSH_PATH
+    $KUBECTL_CMD_CONT exec $POD_NAME -- mkdir -p $SSH_PATH
+    $KUBECTL_CMD_CONT cp $AUTHORIZED_KEYS_PATH $POD_NAME:$AUTHORIZED_KEYS_DEST
+    $KUBECTL_CMD_CONT exec $POD_NAME -- chmod 0600 -R $SSH_PATH
+    $KUBECTL_CMD_CONT exec $POD_NAME -- chown root:root -R $SSH_PATH
     set +e
 }
 start_ssh_server() {
     set -e
     POD_IP=$($KUBECTL_CMD get pods $POD_NAME -o jsonpath='{.status.podIP}')
     echo "Starting dropbear SSH server in $POD_NAME. It is now accessible on $POD_IP (port $PORT)"
-    $KUBECTL_CMD exec $POD_NAME -- mkdir -p /etc/dropbear
-    $KUBECTL_CMD exec -it $POD_NAME -- $PAYLOAD_PATH -RFEs -p $PORT
+    $KUBECTL_CMD_CONT exec $POD_NAME -- mkdir -p /etc/dropbear
+    $KUBECTL_CMD_CONT exec -it $POD_NAME -- $PAYLOAD_PATH -RFEs -p $PORT
     set +e
 }
 
 cleanup() {
     set -e
     echo "Cleanup Enabled. Initiating Cleanup"
-    $KUBECTL_CMD exec $POD_NAME -- rm $AUTHORIZED_KEYS_DEST
-    $KUBECTL_CMD exec $POD_NAME -- rm -rf /etc/dropbear
-    $KUBECTL_CMD exec $POD_NAME -- rm $PAYLOAD_PATH
-    $KUBECTL_CMD exec $POD_NAME -- rm $REMOTE_SCP_PATH
+    $KUBECTL_CMD_CONT exec $POD_NAME -- rm $AUTHORIZED_KEYS_DEST
+    $KUBECTL_CMD_CONT exec $POD_NAME -- rm -rf /etc/dropbear
+    $KUBECTL_CMD_CONT exec $POD_NAME -- rm $PAYLOAD_PATH
+    $KUBECTL_CMD_CONT exec $POD_NAME -- rm $REMOTE_SCP_PATH
     set +e
 }
 
