add scp support and build tweak

diff --git a/bin/kubectl-sshd b/bin/kubectl-sshd
--- a/bin/kubectl-sshd
+++ b/bin/kubectl-sshd
@@ -2,11 +2,12 @@
 
 # Created by argbash-init v2.8.1
 # ARG_POSITIONAL_SINGLE([pod],[Pod name],[])
-# ARG_OPTIONAL_SINGLE([local-dropbear-path],[l],[Local Path to statically-built dropbear/SSH server binary],[static-dropbear])
+# ARG_OPTIONAL_SINGLE([local-dropbear-path],[l],[Local Path to statically-built dropbear/SSH server binary (default: $SCRIPT_DIR/static-dropbear)],[])
 # ARG_OPTIONAL_SINGLE([remote-dropbear-dir],[r],[Pod Path to upload dropbear/SSH server to],[/tmp])
+# ARG_OPTIONAL_SINGLE([remote-scp-path],[R],[Pod Path for scp],[/bin/scp])
 # ARG_OPTIONAL_SINGLE([bind-port],[b],[Pod Bind Port for dropbear/SSH server to],[22])
 # ARG_OPTIONAL_SINGLE([authorized-keys-path],[k],[Public keys of those authorized to authenticate through SSH],[id_rsa.pub])
-# ARG_OPTIONAL_SINGLE([ssh-path],[S],[SSH Path Location, specify if authenticate using non-root user],[/root/.ssh])
+# ARG_OPTIONAL_SINGLE([ssh-path],[s],[SSH Path Location, specify if authenticate using non-root user],[/root/.ssh])
 # ARG_OPTIONAL_SINGLE([namespace],[n],[Pod Namespace],[])
 # ARG_OPTIONAL_BOOLEAN([cleanup],[c],[Cleanup all the files and dropbear binary before script exits])
 # ARG_OPTIONAL_BOOLEAN([verbose],[V],[Increase verbosity of script])
@@ -33,7 +34,7 @@ die()
 
 begins_with_short_option()
 {
-  local first_option all_short_options='lrbkSncVhv'
+  local first_option all_short_options='lrRbksncVhv'
   first_option="${1:0:1}"
   test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -42,8 +43,9 @@ begins_with_short_option()
 _positionals=()
 _arg_pod=
 # THE DEFAULTS INITIALIZATION - OPTIONALS
-_arg_local_dropbear_path="static-dropbear"
+_arg_local_dropbear_path=
 _arg_remote_dropbear_dir="/tmp"
+_arg_remote_scp_path="/bin/scp"
 _arg_bind_port="22"
 _arg_authorized_keys_path="id_rsa.pub"
 _arg_ssh_path="/root/.ssh"
@@ -55,13 +57,14 @@ _arg_verbose="off"
 print_help()
 {
   printf '%s\n' "kssh - Start a SSH server in any Pod"
-  printf 'Usage: %s [-l|--local-dropbear-path <arg>] [-r|--remote-dropbear-dir <arg>] [-b|--bind-port <arg>] [-k|--authorized-keys-path <arg>] [-S|--ssh-path <arg>] [-n|--namespace <arg>] [-c|--(no-)cleanup] [-V|--(no-)verbose] [-h|--help] [-v|--version] <pod>\n' "$0"
+  printf 'Usage: %s [-l|--local-dropbear-path <arg>] [-r|--remote-dropbear-dir <arg>] [-R|--remote-scp-path <arg>] [-b|--bind-port <arg>] [-k|--authorized-keys-path <arg>] [-s|--ssh-path <arg>] [-n|--namespace <arg>] [-c|--(no-)cleanup] [-V|--(no-)verbose] [-h|--help] [-v|--version] <pod>\n' "$0"
   printf '\t%s\n' "<pod>: Pod name"
-  printf '\t%s\n' "-l, --local-dropbear-path: Local Path to statically-built dropbear/SSH server binary (default: 'static-dropbear')"
+  printf '\t%s\n' "-l, --local-dropbear-path: Local Path to statically-built dropbear/SSH server binary (default: $SCRIPT_DIR/static-dropbear) (no default)"
   printf '\t%s\n' "-r, --remote-dropbear-dir: Pod Path to upload dropbear/SSH server to (default: '/tmp')"
+  printf '\t%s\n' "-R, --remote-scp-path: Pod Path for scp (default: '/bin/scp')"
   printf '\t%s\n' "-b, --bind-port: Pod Bind Port for dropbear/SSH server to (default: '22')"
   printf '\t%s\n' "-k, --authorized-keys-path: Public keys of those authorized to authenticate through SSH (default: 'id_rsa.pub')"
-  printf '\t%s\n' "-S, --ssh-path: SSH Path Location, specify if authenticate using non-root user (default: '/root/.ssh')"
+  printf '\t%s\n' "-s, --ssh-path: SSH Path Location, specify if authenticate using non-root user (default: '/root/.ssh')"
   printf '\t%s\n' "-n, --namespace: Pod Namespace (no default)"
   printf '\t%s\n' "-c, --cleanup, --no-cleanup: Cleanup all the files and dropbear binary before script exits (off by default)"
   printf '\t%s\n' "-V, --verbose, --no-verbose: Increase verbosity of script (off by default)"
@@ -99,6 +102,17 @@ parse_commandline()
       -r*)
         _arg_remote_dropbear_dir="${_key##-r}"
         ;;
+      -R|--remote-scp-path)
+        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+        _arg_remote_scp_path="$2"
+        shift
+        ;;
+      --remote-scp-path=*)
+        _arg_remote_scp_path="${_key##--remote-scp-path=}"
+        ;;
+      -R*)
+        _arg_remote_scp_path="${_key##-R}"
+        ;;
       -b|--bind-port)
         test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
         _arg_bind_port="$2"
@@ -121,7 +135,7 @@ parse_commandline()
       -k*)
         _arg_authorized_keys_path="${_key##-k}"
         ;;
-      -S|--ssh-path)
+      -s|--ssh-path)
         test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
         _arg_ssh_path="$2"
         shift
@@ -129,8 +143,8 @@ parse_commandline()
       --ssh-path=*)
         _arg_ssh_path="${_key##--ssh-path=}"
         ;;
-      -S*)
-        _arg_ssh_path="${_key##-S}"
+      -s*)
+        _arg_ssh_path="${_key##-s}"
         ;;
       -n|--namespace)
         test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
@@ -226,10 +240,20 @@ assign_positional_args 1 "${_positionals[@]}"
 # [ <-- needed because of Argbash
 
 
+# resolve actual directory where script resides
+SOURCE="${BASH_SOURCE[0]}"
+while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
+  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
+  SOURCE="$(readlink "$SOURCE")"
+  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
+done
+SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
+
 POD_NAME=$_arg_pod
 SOURCE_PATH=$_arg_local_dropbear_path
 PAYLOAD_DIR=$_arg_remote_dropbear_dir
 PAYLOAD_PATH="${PAYLOAD_DIR}/dropbear"
+REMOTE_SCP_PATH=$_arg_remote_scp_path
 PORT=$_arg_bind_port
 AUTHORIZED_KEYS_PATH=$_arg_authorized_keys_path
 NAMESPACE=$_arg_namespace
@@ -238,6 +262,10 @@ SSH_PATH=$_arg_ssh_path
 KUBECTL_CMD="kubectl"
 AUTHORIZED_KEYS_DEST="${SSH_PATH}/authorized_keys"
 
+if [ -z "$SOURCE_PATH" ];
+then
+    SOURCE_PATH="${SCRIPT_DIR}/static-dropbear"
+fi
 
 if [ ! -z "$NAMESPACE" ];
 then
@@ -260,6 +288,15 @@ copy_binary() {
         if [ $? -eq 0 ]
         then
             echo "Payload uploaded to $PAYLOAD_PATH!"
+            if [ ! -z "${REMOTE_SCP_PATH}" ]
+            then
+                echo "Setting up scp symlink $REMOTE_SCP_PATH -> $PAYLOAD_PATH"
+                $KUBECTL_CMD exec $POD_NAME -- ln -s $PAYLOAD_PATH $REMOTE_SCP_PATH
+                if [ $? -ne 0 ]
+                then
+                    echo "Failed to symlink scp $REMOTE_SCP_PATH -> $PAYLOAD_PATH. Ignoring."
+                fi
+            fi
         else
             echo "Payload failed to upload. Aborting."
             cat << EOF
@@ -304,6 +341,7 @@ cleanup() {
     $KUBECTL_CMD exec $POD_NAME -- rm $AUTHORIZED_KEYS_DEST
     $KUBECTL_CMD exec $POD_NAME -- rm -rf /etc/dropbear
     $KUBECTL_CMD exec $POD_NAME -- rm $PAYLOAD_PATH
+    $KUBECTL_CMD exec $POD_NAME -- rm $REMOTE_SCP_PATH
     set +e
 }
 
